# Generated by Django 4.2.5 on 2023-09-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_rsp', models.CharField(max_length=2000)),
                ('audio_rsp', models.CharField(max_length=4000)),
            ],
        ),
    ]
